version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: music_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - music_network

networks:
  music_network:
    driver: bridge